### ISSUE TITLE
Не для всех изменений нужны комментарии от бота

### ISSUE THREAD

**Issue by dreamore** [eugenedotru/jira_watcher#5]
Есть ряд полей, которые несут чисто технический характер и их изменения не нужно отслеживать.
Пример таких полей:
- Дата окончания тестирования 
- Время тестирования

**Comment by eugenedotru** [comment]
Сейчас будут приходить сообщения в следующих случаях:
- Сменился приоритет задачи;
- сменился тип задачи;
- сменилось наименование задачи;
- сменился ответственный за задачу;
- сменился статус задачи;
- задача была прокомментирована.
